/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Local_Sales;

import userInterface.Sales.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Role.PMRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LocalRequest;

import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.WorkRequest.Language;
import Business.WorkQueue.WorkRequest.contentType;
import Business.WorkQueue.WorkRequest.workStatus;
import java.awt.CardLayout;
import java.awt.Component;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.PMs.PMsWorkAreaJPanel;
import userInterface.Trans.TransWorkAreaJPanel;

/**
 *
 * @author Yin
 */
public class LocalcreateWorkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createWorkJPanel
     */
    String path;
    
    JPanel upc;
    EcoSystem system;
    Enterprise enterprise;
    UserAccount LocalSRaccount;


    LocalcreateWorkJPanel(JPanel upc, Enterprise enterprise, UserAccount account) {
        initComponents();
        this.upc = upc;
        this.enterprise = enterprise;
        this.LocalSRaccount = account;
        populateCombo();
    }
    
    public void populateCombo(){
        cbArticleType.removeAllItems();
        for(contentType type: WorkRequest.contentType.values()){
            cbArticleType.addItem(type.toString());
        }
        
        cbSource.removeAllItems();
        cbDestination.removeAllItems();
        for(Language language: WorkRequest.Language.values()){
            cbSource.addItem(language.name());
            cbDestination.addItem(language.name());
        }

        cbPM.removeAllItems();
        for(UserAccount ua: enterprise.getUserAccountDirectory().getUserAccountList()){
            if(ua.getRole().toString().equals("LocalPMRole")){
                cbPM.addItem(ua.getEmployee().getName());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnSubmit = new javax.swing.JButton();
        txtCustomer = new javax.swing.JTextField();
        cbArticleType = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        spinnerPrice = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        txtWords = new javax.swing.JTextField();
        cbSource = new javax.swing.JComboBox<>();
        cbDestination = new javax.swing.JComboBox<>();
        cbPM = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSample = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        SliderPrice = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Customer：");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Article Type: ");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Import Article:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Unit Price(thousand words): $");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Source Language: ");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Select Project Manager: ");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Destination Language: ");

        BtnSubmit.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        BtnSubmit.setText("Submit");
        BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitActionPerformed(evt);
            }
        });

        cbArticleType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("Choose the file");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        spinnerPrice.setModel(new javax.swing.SpinnerNumberModel(80.0d, 5.0d, 150.0d, 5.0d));
        spinnerPrice.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerPriceStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Word Count: ");

        cbSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSourceActionPerformed(evt);
            }
        });

        cbDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDestinationActionPerformed(evt);
            }
        });

        cbPM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPMActionPerformed(evt);
            }
        });

        txtSample.setColumns(20);
        txtSample.setLineWrap(true);
        txtSample.setRows(5);
        txtSample.setToolTipText("");
        txtSample.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txtSample);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Sample: ");

        jButton3.setText("← Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        SliderPrice.setMajorTickSpacing(10);
        SliderPrice.setMinimum(10);
        SliderPrice.setValue(60);
        SliderPrice.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderPriceStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Jazz LET", 0, 24)); // NOI18N
        jLabel10.setText("CreateLocalization Work");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(19, 19, 19)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SliderPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbArticleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWords, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(BtnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(spinnerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(cbArticleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButton2))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cbPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SliderPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtWords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSubmit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSourceActionPerformed

    private void cbDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDestinationActionPerformed

    private void cbPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPMActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser imgc = new JFileChooser();
        imgc.setFileSelectionMode(JFileChooser.FILES_ONLY );
        int i = imgc.showOpenDialog(null);
        try{
            if(i== imgc.APPROVE_OPTION){ //打开文件
            path = imgc.getSelectedFile().getAbsolutePath();
            String name = imgc.getSelectedFile().getName();
            System.out.println("当前文件路径："+path+";\n当前文件名："+name);
            BufferedReader reader = new BufferedReader(new FileReader(path));//换成你的文件名   
            String line = null; 

            while((line=reader.readLine())!=null){
                String Item = line;
           //   String Items[] = line.split(",");
                String[] Words = line.split(" ");
                System.out.println(Words.length);
                txtSample.setText(Item);
                txtWords.setText(String.valueOf(Words.length));
   
System.out.println(Item);
                
            }
        }else{
            System.out.println("没有选中文件");
        }
        }catch(Exception e){
           e.printStackTrace();
        }
        
       
/*
        ImageIcon icon = new ImageIcon(path);
        icon.setImage(icon.getImage().getScaledInstance(145,155,Image.SCALE_DEFAULT));
        picUpLabel.setIcon(icon);
*/

    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitActionPerformed
        // TODO add your handling code here:
        if(txtCustomer.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Input customerName");
        }else if(txtSample.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Upload your file");
        
        }else if(cbSource.getSelectedItem().toString().equals(cbDestination.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null,"Destination Language should not be same with Source Language");
        
        }else{
            
            String custName = txtCustomer.getText();
            String articleType = cbArticleType.getSelectedItem().toString();
            String content = txtSample.getText();
            double unitPrice = (double) spinnerPrice.getValue();
            int wordCount = Integer.parseInt(txtWords.getText());
        
            String srcLanguage =  cbSource.getSelectedItem().toString();
            String desLanguage =  cbDestination.getSelectedItem().toString();
        
            String PMName = cbPM.getSelectedItem().toString();
            UserAccount PM = enterprise.getUserAccountDirectory().findUserAccountByName(PMName);
        
            LocalRequest lr =   enterprise.getWorkQueue().addLocalizationRequest();
        
            lr.setLocalSR(LocalSRaccount);   //
            lr.setCustomerName(custName);
            lr.setContent(content);
            lr.setContentType(articleType);
            lr.setLocalizeUnitPrice(unitPrice); //
            lr.setWordCount(wordCount);
            lr.setSourceLanguage(srcLanguage);
            lr.setDestinationLanguage(desLanguage);
            lr.setLocalPM(PM);  //
        
            
            JOptionPane.showMessageDialog(null,"Mission Created");
            
            upc.remove(this);
             Component[] componentArray = upc.getComponents();
             Component component = componentArray[componentArray.length - 1];
             LocalSalesWorkAreaJPanel lswap = (LocalSalesWorkAreaJPanel) component;
             lswap.populateTable();
             CardLayout layout = (CardLayout) upc.getLayout();
             layout.previous(upc);

System.out.println(lr.getRequestDate());
        
        }
        
        
    }//GEN-LAST:event_BtnSubmitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        Component[] componentArray = upc.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LocalSalesWorkAreaJPanel lswap = (LocalSalesWorkAreaJPanel) component;
        lswap.populateTable();
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SliderPriceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderPriceStateChanged
        // TODO add your handling code here:
        double Price = SliderPrice.getValue();
        spinnerPrice.setValue(Price);
    }//GEN-LAST:event_SliderPriceStateChanged

    private void spinnerPriceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerPriceStateChanged
        // TODO add your handling code here:
        double Price = (double) spinnerPrice.getValue();
        SliderPrice.setValue((int) Price);
    }//GEN-LAST:event_spinnerPriceStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JSlider SliderPrice;
    private javax.swing.JComboBox<String> cbArticleType;
    private javax.swing.JComboBox<String> cbDestination;
    private javax.swing.JComboBox<String> cbPM;
    private javax.swing.JComboBox<String> cbSource;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinnerPrice;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextArea txtSample;
    private javax.swing.JTextField txtWords;
    // End of variables declaration//GEN-END:variables
}
