/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.LRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.LocalizationEnterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LocalRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author qwe09
 */
public class ProfitJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfitJPanel
     */
             JPanel upc;
    JPanel jp;
    ArrayList<String> p;
    UserAccount Transaccount;
    Enterprise enterprise;
    WorkRequest wr;
    
    public ProfitJPanel(JPanel userProcessContainer, JPanel jp, Enterprise enterprise, EcoSystem system) {
        initComponents();
                 this.upc = userProcessContainer;
          this.jp = jp;
          this.p=p;
          this.enterprise= enterprise;
          pop();
    }

    void pop()
    {
          DefaultTableModel model = (DefaultTableModel) PT.getModel();
        
        model.setRowCount(0);
        double p=0;
            double pp=0;
            int n=0;
        for (int i=0;i<enterprise.getUserAccountDirectory().getUserAccountList().size();i++){
            Object[] row = new Object[3];
               
            if(enterprise.getUserAccountDirectory().getUserAccountList().get(i).getRole().toString().equals("LocalPMRole"))
            {
              
                row[0] = enterprise.getUserAccountDirectory().getUserAccountList().get(i).getUsername();
              
                   for(int j=0;j<enterprise.getWorkQueue().getWorkRequestList().size();j++)
            { 
                LocalRequest lr = (LocalRequest)enterprise.getWorkQueue().getWorkRequestList().get(j);
                if(lr.getLocalPM().getUsername().equals(row[0]))
              {
             
                p=p+lr.getLocalizeUnitPrice() - lr.getUnitPrice();
                pp=p/lr.getUnitPrice();
                n++;
                 }
                
            }
            if(n==0)
            {
                row[1]=0;
            }
            else
                    {
                         row[1] = p/n;
                    }
           
             row[2] = pp;
             model.addRow(row);
             
           
            }
            
              p=0;
               pp=0;
               n=0;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PT = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        PT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PM", "Profit", "Ratio"
            }
        ));
        jScrollPane1.setViewportView(PT);
        if (PT.getColumnModel().getColumnCount() > 0) {
            PT.getColumnModel().getColumn(2).setResizable(false);
        }

        backJButton.setText("<-Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Manage Profit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(backJButton)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(backJButton)
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PT;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
