/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Trans;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.TransOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.WorkRequest.workStatus;
import java.awt.CardLayout;
import java.awt.Image;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yin
 */
public class TransWorkAreaJPanel extends javax.swing.JPanel {

    JPanel upc;
    UserAccount Transaccount;
    Enterprise enterprise;
    Organization organization;
    Network network;
    JPanel jp;

    public TransWorkAreaJPanel(JPanel userProcessContainer,JPanel jp, UserAccount account, Enterprise enterprise, TransOrganization organization,Network network) {
        initComponents();
        this.upc = userProcessContainer;
        this.jp = jp;
        this.Transaccount = account;
        this.enterprise = enterprise;
        this.organization = organization;
        this.network = network;
        populateTable();
        
        ImageIcon icon = new ImageIcon("image/keyword5.png");
        icon.setImage(icon.getImage().getScaledInstance(382,175,Image.SCALE_DEFAULT));
        picLabel.setIcon(icon);

    }

    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblTranslation.getModel();
        dtm.setRowCount(0);
        
        for(Enterprise e: network.getEnterpriseDirectory().getEnterpriseList()){
            for(WorkRequest wr: e.getWorkQueue().getWorkRequestList()){ 
                if(wr.getTL() == Transaccount){
                Object[] row = new Object[7];
                row[0] = wr;
                row[1] = wr.getRequestDate();
                row[2] = wr.getSR().getEmployee().getName();
                row[3] = wr.getSourceLanguage() + " → " +wr.getDestinationLanguage();
                row[4] = wr.getWordCount();
                row[5] = wr.getContentType();
                row[6] = wr.getStatus();
                dtm.addRow(row);
            }
                       long diff;
            long days=0;
            double n=0;
            DecimalFormat df = new DecimalFormat( "0.0000 "); 
            for(int i=0;i<e.getWorkQueue().getWorkRequestList().size();i++)
            {
                if(e.getWorkQueue().getWorkRequestList().get(i).getResolveDate()!=null)
                {
                    diff = e.getWorkQueue().getWorkRequestList().get(i).getResolveDate().getTime() - e.getWorkQueue().getWorkRequestList().get(i).getRequestDate().getTime();
                    days = days+diff/(60*60);
                    n=e.getWorkQueue().getWorkRequestList().get(i).getWordCount()+n;
                }
                else
                {
                    n=n+0;
                    days=days+0;
                    
                }
                
            }
            if(days==0)
            {
                TF.setText(String.valueOf(0));
            }
            else
            {
                TF.setText(String.valueOf(df.format(n/days)));
                Transaccount.setTime(Double.parseDouble(df.format(n/days)));
                System.out.println(n);
                System.out.println(days);
            }     
                
        }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTranslation = new javax.swing.JTable();
        TF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        picLabel = new javax.swing.JLabel();

        jButton1.setText("Start this work");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblTranslation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Article ID", "StartDate", "Sales Name", "Src→Dest", "Word Count", "Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTranslation);

        TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Jazz LET", 3, 18)); // NOI18N
        jLabel1.setText("Translation WorkList：");

        picLabel.setText("_");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(picLabel)
                .addGap(0, 408, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(picLabel)
                .addGap(0, 150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TF, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblTranslation.getSelectedRow();
        if(selectedRow >= 0){
            
           
            WorkRequest wr = (WorkRequest) tblTranslation.getValueAt(selectedRow,0);
            if(wr.getStatus().equals(workStatus.Translated.name())){
                JOptionPane.showMessageDialog(null,"Work Finished");
            }else{
                wr.setStatus(workStatus.Translating.name());
                TranslatingJPanel tljp = new TranslatingJPanel(upc,Transaccount,wr);
                upc.add("TranslatingJPanel",tljp);
                CardLayout layout = (CardLayout) upc.getLayout();
                layout.next(upc);
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Please select one of your work");
        }

      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel picLabel;
    private javax.swing.JTable tblTranslation;
    // End of variables declaration//GEN-END:variables
}
