/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Local_PMs;

import Business.Enterprise.LocalizationEnterprise;
import userInterface.Trans.*;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author qwe09
 */
public class BarJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BarJPanel
     */
    
       JPanel upc;
    JPanel jp;
    ArrayList<String> p;
    UserAccount Transaccount;
    LocalizationEnterprise enterprise;
    WorkRequest wr;

    public BarJPanel(JPanel userProcessContainer, JPanel jp, LocalizationEnterprise enterprise, ArrayList<String> p) {
        initComponents();
                  this.upc = userProcessContainer;
          this.jp = jp;
          this.p=p;
          this.enterprise= enterprise;
       //this.Transaccount = Transaccount;
      // this.wr = wr;
  
       //upc.removeAll();
     // jp.setLayout(null);
      jp.setPreferredSize(new Dimension(100, 100));
        JPanel n= new ChartPanel(CreateBarJPanel());
         upc.add(n);
          JButton newButton = new JButton("<Back");
      newButton.setPreferredSize(new java.awt.Dimension(33,33));
      jp.add(newButton);
newButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                upc.remove(n);
                upc.remove(1);
                CardLayout layout = (CardLayout) upc.getLayout();
                
        layout.previous(upc);
        newButton.setSize(0,0);
        jp.remove(newButton);
                        CardLayout layout1 = (CardLayout) jp.getLayout();
                
        layout1.previous(jp);
        
                System.out.println("触发了事件");
            }
        });
       
    }
JFreeChart CreateBarJPanel()
    {
                 DefaultCategoryDataset mDataset = new DefaultCategoryDataset();   
                 for(int i=0;i< enterprise.getSupplierDirectory().getSupplierList().size();i++){
                 
                         mDataset.addValue(Double.parseDouble(p.get(i)), enterprise.getSupplierDirectory().getSupplierList().get(i).getTranslationEnterprise(), "Translator");  
                     
                 }
     
        //Create JFreeChart object
      JFreeChart mBarChart = ChartFactory.createBarChart(  
                "The average efficiency of translator",  //图表标题  
                "Translator",       //横轴（目录轴）标签  
                "Average efficiency",           //纵轴（数值轴）标签  
                mDataset,       //数据集  
                PlotOrientation.VERTICAL,   //图表方向  
                true,           //是否显示图例  
                true,           //是否生成提示工具  
                false);         //是否生成url连接  
      
        return mBarChart;
        
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
