/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.TRole;

import userInterface.LRole.*;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.LocalizationEnterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LocalRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author qwe09
 */
public class ProfitJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfitJPanel
     */
            JPanel upc;
    JPanel jp;
    ArrayList<String> p;
    UserAccount Transaccount;
    Enterprise enterprise;
    WorkRequest wr;
    
    public ProfitJPanel(JPanel userProcessContainer, JPanel jp, Enterprise enterprise, EcoSystem system) {
        initComponents();
                 this.upc = userProcessContainer;
          this.jp = jp;
          this.p=p;
          this.enterprise= enterprise;
          pop();
    }

    void pop()
    {
          DefaultTableModel model = (DefaultTableModel) PT.getModel();
        
        model.setRowCount(0);
        double p=0;
            double pp=0;
            int n=0;
        for (int i=0;i<enterprise.getUserAccountDirectory().getUserAccountList().size();i++){
            Object[] row = new Object[3];
               
            if(enterprise.getUserAccountDirectory().getUserAccountList().get(i).getRole().toString().equals("PMRole"))
            {
              
                row[0] = enterprise.getUserAccountDirectory().getUserAccountList().get(i).getUsername();
              
                   for(int j=0;j<enterprise.getWorkQueue().getWorkRequestList().size();j++)
            { 
               
                if(enterprise.getWorkQueue().getWorkRequestList().get(j).getPM().getUsername().equals(row[0]))
              {
                  double pr=0;
                  if(enterprise.getWorkQueue().getWorkRequestList().get(j).getTL()!=null)
                  {
             for(int k=0;k<enterprise.getWorkQueue().getWorkRequestList().get(j).getTL().getAbilityDirectory().getAbilityList().size();k++)
             {
                 if(enterprise.getWorkQueue().getWorkRequestList().get(j).getDestinationLanguage().equals(enterprise.getWorkQueue().getWorkRequestList().get(j).getTL().getAbilityDirectory().getAbilityList().get(k).getDestination())
                         && enterprise.getWorkQueue().getWorkRequestList().get(j).getSourceLanguage().equals(enterprise.getWorkQueue().getWorkRequestList().get(j).getTL().getAbilityDirectory().getAbilityList().get(k).getSource()))
                 {
                     pr=enterprise.getWorkQueue().getWorkRequestList().get(j).getTL().getAbilityDirectory().getAbilityList().get(k).getUnitPrice();
                 }
             }
                  }

                p=p+enterprise.getWorkQueue().getWorkRequestList().get(j).getUnitPrice()-pr;
                pp=p/enterprise.getWorkQueue().getWorkRequestList().get(j).getUnitPrice();
                n++;
                 }
                
            }
            if(n==0)
            {
                row[1]=0;
            }
            else
                    {
                         row[1] = p/n;
                    }
           
             row[2] = pp;
             model.addRow(row);
             
           
            }
            
              p=0;
               pp=0;
               n=0;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PT = new javax.swing.JTable();
        backjButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        PT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PM", "Profit", "Ratio"
            }
        ));
        jScrollPane1.setViewportView(PT);
        if (PT.getColumnModel().getColumnCount() > 0) {
            PT.getColumnModel().getColumn(2).setResizable(false);
        }

        backjButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backjButton1.setText("<- Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Manage Profit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(backjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backjButton1)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PT;
    private javax.swing.JButton backjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
